version: '3'

services:
  nginx:
    build: ./nginx/
    container_name: ng01
    ports:
      - "80:80"
    volumes:
      - ./public:/code/public
      - ./nginx/conf:/etc/nginx/conf.d
    depends_on:
      - web
  db:
    image: postgres
    ports:
      - '127.0.0.1:5432:5432'
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    healthcheck:
        test: exit 0
  web:
    build: .
    command: gunicorn sigecc.wsgi:application -w 3 -b 0.0.0.0:8000
    environment:
      - APP_ENV=production
    ports:
      - "8000:8000"
    volumes:
      - ./public:/code/public
    depends_on:
      - db

volumes:
  pgdata:
  public:
