version: '3'

services:
  db:
    image: postgres
    ports:
      - '127.0.0.1:5432:5432'
    volumes:
      - ./pgdata:/var/lib/postgresql/data
  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  pgdata:
