# Generated by Django 2.0.6 on 2018-06-21 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupo',
            name='nome',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='modulo',
            name='liberado',
            field=models.BooleanField(default=False),
        ),
    ]
