# Generated by Django 2.0.6 on 2018-07-01 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='perfilresposta',
            unique_together={('pergunta', 'resposta', 'aluno')},
        ),
    ]
