# Generated by Django 2.0.6 on 2018-07-08 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20180703_0113'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerguntaFlow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pergunta', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='RespostaFlow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resposta', models.IntegerField()),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='alunoresposta',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='alunoresposta',
            name='aluno',
        ),
        migrations.RemoveField(
            model_name='alunoresposta',
            name='pergunta',
        ),
        migrations.AlterModelOptions(
            name='placar',
            options={'ordering': ('-pontos',)},
        ),
        migrations.AlterField(
            model_name='aluno',
            name='grupo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Grupo'),
        ),
        migrations.AlterField(
            model_name='grupoquestaoaluno',
            name='resposta',
            field=models.CharField(blank=True, choices=[('opcao1', 'Opção 1'), ('opcao2', 'Opção 2'), ('opcao3', 'Opção 3'), ('opcao4', 'Opção 4'), ('opcao5', 'Opção 5')], max_length=6),
        ),
        migrations.DeleteModel(
            name='AlunoResposta',
        ),
        migrations.AddField(
            model_name='respostaflow',
            name='aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Aluno'),
        ),
        migrations.AddField(
            model_name='respostaflow',
            name='pergunta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.PerguntaFlow'),
        ),
        migrations.AlterUniqueTogether(
            name='respostaflow',
            unique_together={('pergunta', 'resposta', 'aluno')},
        ),
    ]
