# Generated by Django 2.0.6 on 2018-09-04 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20180708_1132'),
    ]

    operations = [
        migrations.CreateModel(
            name='Desafio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('pontos', models.IntegerField()),
                ('modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Modulo')),
            ],
        ),
        migrations.CreateModel(
            name='DesafioGrupo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desafio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Desafio')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Grupo')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='desafiogrupo',
            unique_together={('desafio', 'grupo')},
        ),
    ]
