# Generated by Django 2.0.6 on 2018-09-04 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20180904_1837'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='desafio',
            options={'ordering': ('id',)},
        ),
        migrations.RemoveField(
            model_name='desafio',
            name='modulo',
        ),
    ]
