# Generated by Django 2.0.6 on 2019-04-14 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_modulo_finalizado'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulo',
            name='nome',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
