# Generated by Django 2.0.6 on 2019-04-14 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_modulo_nome'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pergunta',
            name='titulo',
        ),
        migrations.AddField(
            model_name='pergunta',
            name='enunciado',
            field=models.TextField(blank=True),
        ),
    ]
