# Generated by Django 2.0.6 on 2019-04-14 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_questao_texto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pergunta',
            name='questao',
        ),
        migrations.AddField(
            model_name='questao',
            name='perguntas',
            field=models.ManyToManyField(to='core.Pergunta'),
        ),
    ]
