# Generated by Django 2.0.6 on 2019-04-14 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20190414_2008'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupo',
            name='quantidade',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
