# Generated by Django 2.0.6 on 2019-04-20 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_grupo_quantidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='foto',
            field=models.ImageField(null=True, upload_to='fotos/%Y/%m/%d/'),
        ),
    ]
