# Generated by Django 2.0.6 on 2019-04-20 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_aluno_foto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno',
            name='foto',
        ),
        migrations.AddField(
            model_name='grupo',
            name='foto',
            field=models.ImageField(null=True, upload_to='fotos/%Y/%m/%d/'),
        ),
    ]
