# Generated by Django 2.0.6 on 2019-04-21 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_grupoquestao_resposta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grupoquestao',
            name='atribuicoes',
        ),
        migrations.AddField(
            model_name='grupoquestao',
            name='respondedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Aluno'),
        ),
    ]
