# Generated by Django 2.0.6 on 2019-04-21 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20190421_1706'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questao',
            name='perguntas',
        ),
        migrations.AddField(
            model_name='questao',
            name='pergunta',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Pergunta'),
            preserve_default=False,
        ),
    ]
