# Generated by Django 2.0.6 on 2019-04-21 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20190421_1758'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='desafiogrupo',
            options={'ordering': ('desafio__pk',)},
        ),
    ]
