# Generated by Django 2.0.6 on 2019-04-22 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20190421_1925'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupo',
            name='fotografo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fotografo', to='core.Aluno'),
        ),
    ]
