# Generated by Django 2.0.6 on 2019-05-09 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_grupo_fotografo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perguntaflow',
            options={'ordering': ('id',)},
        ),
    ]
