# Generated by Django 2.0.6 on 2019-05-22 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20190509_1650'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='placar',
            options={'ordering': ('-pontos', '-grupo__acertos')},
        ),
    ]
